[project]
name = "btc-rpc-data"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ccxt>=4.5.30",
    "cryptoexplorer>=1.3",
    "numpy>=2.4.0",
    "pandas[parquet]>=2.3.3",
]
